hotel=[
    {
        "City": "Ibshway",
        "Double": 13,
        "Phone": "(+20)1090244474",
        "Single": 0,
        "Sweet": 7,
        "TotalBeds": 0,
        "Triple": 3,
        "address": "On the coast of Lake Qarun",
        "chalet": 0,
        "coordinatesX": 29.465014756799736,
        "coordinatesY": 30.721956188757137,
        "description": "Offering lake views, New Panorama Resort B&B is located in the center of Fayoum, a restaurant, a 24-hour front desk, bar, garden, year-round outdoor pool and sun terrace. The B&B includes free private parking and free WiFi.\nAll units include a seating area, a flat-screen TV with satellite channels and a private bathroom with free toiletries, bidet, shower and bath. Each unit also offers a patio with pool views.\nGuests at New Panorama Resort bed and breakfast can enjoy a continental breakfast.\nThis property provides a private beach area and a shared lounge.",
        "email": "atef.younan111@gmail.com",
        "id": 4,
        "name": "Panorama",
        "originalImage": "image/171066468.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://www.facebook.com/NewPanoramaResort"
    },
    {
        "City": "Snores",
        "Double": 0,
        "Phone": "(+20)84-830-999",
        "Single": 0,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "On the coast of Lake Qarun",
        "chalet": 0,
        "coordinatesX": 29.474210159050614,
        "coordinatesY": 30.73794959796282,
        "description": "Facing the beachfront, Fayoum Hotel Armed Forces offers 4-star accommodations in ‘Ezbet Sa‘dî Mugâwir and features a garden, terrace and restaurant. This 4-star hotel offers room service, a 24-hour front desk and free WiFi. Private parking is available on site.\n\nAt the hotel every room comes with air conditioning, a closet, a balcony with a lake view, a private bathroom, a flat-screen TV, bed linen and towels. Fayoum Hotel Armed Forces provides certain units with garden views, and the rooms include an electric tea pot. All guest rooms will provide guests with a fridge.\n\nA continental breakfast is available daily at the accommodation.\n\nFayoum Hotel Armed Forces has an outdoor pool.\n\nThe nearest airport is Sphinx International Airport, 99.8 km from the hotel.",
        "email": "",
        "id": 5,
        "name": "Armed Forces",
        "originalImage": "image/308415270.jpg",
        "user_id": 5,
        "villa": 0,
        "web": ""
    },
    {
        "City": "fayoum",
        "Double": 11,
        "Phone": "(+20)084-2204339",
        "Single": 3,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 2,
        "address": "Lotfallah facility",
        "chalet": 0,
        "coordinatesX": 29.313389784178938,
        "coordinatesY": 30.841417446513464,
        "description": "Located in Fayoum, 41.8 km from Railway Station - Beni Suef, Queen Hotel Fayoum has air-conditioned accommodations and a restaurant. The property provides room service and a 24-hour front desk for guests.\n\nAll rooms in the hotel are equipped with a flat-screen TV.\n\nGuests at Queen Hotel Fayoum can enjoy a continental breakfast.\n\nThe nearest airport is Sphinx International Airport, 104.6 km from the accommodation.",
        "email": "nashattgh@yahoo.com",
        "id": 6,
        "name": "Queen",
        "originalImage": "image/426673707.jpg",
        "user_id": 5,
        "villa": 0,
        "web": ""
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 8,
        "Phone": "(+20)122-244-0012",
        "Single": 0,
        "Sweet": 4,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "Tunis Village",
        "chalet": 1,
        "coordinatesX": 29.40500408865892,
        "coordinatesY": 30.4844805506587,
        "description": "Kom el Dikka is a 30 year old privately owned Olive Farm located on the hills of Tunis Village in Fayoum overlooking Lake Qarun, which has been recently developed into an Agri-Tourism Lodge. Several years ago, the farm added Vegetable & Fruit Organic Agriculture to its program to accommodate for the family’s’ and relatives needs, and has since expanded to include selling Certified organic products to Tunis Village and Cairo residence.\n\nKom el Dikka accommodates guests in a few secluded locations on the hills of the estate overlooking Lake Qarun. All architecture is in Earth/Islamic design, which is both beautiful and functional, especially in managing hot and dry weather. Making it feel warmer in winter and cooler in summer than the outside temperature.",
        "email": "komeldikkaagrilodge@gmail.com",
        "id": 7,
        "name": "Kom El Dikka Agri Lodge",
        "originalImage": "image/kom-el-dikka-agri-lodge_1.jpg",
        "user_id": 5,
        "villa": 1,
        "web": "www.facebook.com/komeldikkaagrilodge"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 17,
        "Phone": "(+20)100-678-7478",
        "Single": 0,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 4,
        "address": "Tunis Village",
        "chalet": 0,
        "coordinatesX": 29.396214382201197,
        "coordinatesY": 30.495920041916712,
        "description": "Located in the heart of Tunis Village, Sobek Lodge features a garden and free Wi-Fi. It is 14 km away from Wadi El Rayan and just a 5-minute drive from Qaroun Lake. Sobek Lodge has simply decorated rooms with traditional furniture. Each room has a fan, a closet, and a private bathroom with shower. \n\nGuests can enjoy organic, home cooked food before visiting one of the nearby pottery workshops. The lodge can organize for them a variety of activities, including bird watching, yoga, horse riding, and safaris. South-West Cairo and Wadi Hittan are about 80 km away from the property. Free private parking is also available onsite.",
        "email": "",
        "id": 8,
        "name": "Sobek Lodge",
        "originalImage": "image/sobek-lodge-1.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://www.facebook.com/profile.php?id=100057047306493"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 0,
        "Phone": "(+20)109 073 5328",
        "Single": 0,
        "Sweet": 14,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "Tunis Village",
        "chalet": 0,
        "coordinatesX": 29.40366828854982,
        "coordinatesY": 30.48808452191949,
        "description": "Lazib Inn Resort & Spa is located in the magical Tunis village, overlooking Qaroun Lake in Fayoum oasis. This royal country side retreat reflects the marvelous nature of rustic beauty with exceptional personalized services.\nLazib Inn Resort & Spa features 8 Oasis Suites; distinctively designed, each with a unique character, combine style, charm and exquisite attention to details. Those well-appointed suites are 80 m2 feature super king size bed, spacious separate seating areas with unique furnishing and exotic colour accents, a fire place, spacious bathroom with double wash basin, large vanity mirror, towel racks and a glass-walled rain and a separate Jacuzzi tub shower with the magnificent views of Qaroun Lake and surrounded by lavish landscapes that guarantee privacy.\n\nYou will find a 24-hour front desk at the property.\n\nThe area is popular for horse riding, bird-watching and desert safari.",
        "email": "info@lazibinn.com",
        "id": 9,
        "name": "Lazib Inn Resort & Spa",
        "originalImage": "image/general-area-of-the-pool.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://www.lazibinn.com/"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 7,
        "Phone": "(+20)84-682-0180",
        "Single": 5,
        "Sweet": 6,
        "TotalBeds": 0,
        "Triple": 4,
        "address": "Tunis Village",
        "chalet": 1,
        "coordinatesX": 29.40093014879125,
        "coordinatesY": 30.491215959422387,
        "description": "Located in Al Fayyūm, just a 5-minute walk from Qaroun Lake, Zad El Mosafer Guest House has traditionally decorated rooms. It offers an outdoor pool, pottery workshops, and a restaurant.\n\nZad El Mosafer has simply decorated rooms with stone floors, mud brick walls, and colourful rugs. Each of the bright rooms has a closet.\n\nAl Mendada restaurant serves local dishes, in a traditional environment with wooden tables and vaulted ceilings.\n\nGuests can relax in the Bedwen seating area or choose from a variety of activities, including bird watching and camel safaris. A horse riding school and a children’s playground area are also provided.\n\nWadi El-Rayan is 14 km, while Wadi El-Hitan is 80 km away. Free private parking is also available on site.",
        "email": "ezadelmosafer@yahoo.com",
        "id": 10,
        "name": "Zad El Mosafer Guest House",
        "originalImage": "image/55117004.jpg",
        "user_id": 5,
        "villa": 1,
        "web": "https://www.facebook.com/ZadElmosaferHotel"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 7,
        "Phone": "(+20)1093410924",
        "Single": 0,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 2,
        "address": "Tunis Village",
        "chalet": 0,
        "coordinatesX": 29.399611804635697,
        "coordinatesY": 30.485367866262667,
        "description": "Featuring a swimming pool, a garden, a restaurant and views of the garden, Tebtunis is located in ‘Izbat an Nāmūs and provides accommodation with free WiFi.\n\nAll units feature air conditioning and a flat-screen TV.\n\nA halal breakfast is available daily at the lodge.\n\nBoth a bicycle rental service and a car rental service are available at Tebtunis, while cycling can be enjoyed nearby.\n\nThe nearest airport is Cairo International, 141 km from the accommodation, and the property offers a paid airport shuttle service.",
        "email": "",
        "id": 11,
        "name": "Tebtunis",
        "originalImage": "image/364543377.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://www.facebook.com/Tebtunisfayoum"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 8,
        "Phone": "(+20)1005383653",
        "Single": 0,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "Tunis Village",
        "chalet": 0,
        "coordinatesX": 29.395144004132597,
        "coordinatesY": 30.497254320356447,
        "description": "Tunis village Villa is located in Fayoum Center. The accommodations is 93 mi from Cairo.",
        "email": "reservations@tzila.com",
        "id": 12,
        "name": "Tzila Lodge",
        "originalImage": "image/309557710.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://tzila.com/contact-us"
    },
    {
        "City": "Yusuf Al-Sdeek",
        "Double": 6,
        "Phone": "(+20)084-2822672",
        "Single": 3,
        "Sweet": 1,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "Tunis Village",
        "chalet": 0,
        "coordinatesX": 29.40149425571233,
        "coordinatesY": 30.490649215940405,
        "description": "Sun Lake Hotel is located in Fayoum.\n\nEvery unit features a private bathroom and shower, air conditioning, a flat-screen TV and a fridge. Some units include a seating area and/or a balcony.\n\nÀ la carte and halal breakfast options are available daily at the apartment. At Sun Lake Hotel you'll find a restaurant serving Middle Eastern, Local and Grill/Bbq cuisine. Vegetarian and halal options can also be requested.\n\nThe accommodation has a playground.\n\nA terrace can be found at Sun Lake Hotel, along with a garden.\n\nThe nearest airport is Cairo International, 141.6 km from the apartment, and the property offers a paid airport shuttle service.",
        "email": "",
        "id": 13,
        "name": "Sun Lake Hotel",
        "originalImage": "image/362535033.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "https://tunisiarestaurant-fayoum.business.site/"
    },
    {
        "City": "fayoum",
        "Double": 57,
        "Phone": "(+20)84-698-1200",
        "Single": 37,
        "Sweet": 4,
        "TotalBeds": 0,
        "Triple": 3,
        "address": "On the coast of Lake Qarun",
        "chalet": 0,
        "coordinatesX": 29.469007546049834,
        "coordinatesY": 30.77064881937121,
        "description": "Founded in 1937, the luxurious hotel has been the official host of celebrities and prominent figures over the years.\\nSpread over the fabulous coasts of Lake Karoun, the former hunting lodge of King Farouk offers an elegant atmosphere and a number of activities. Enjoy the unspoiled countryside and take a stroll along the golden sandy beach. Go fishing, boat sailing or windsurfing. Take a short excursion to visit the famous Seven Waterwheels or explore the unique rock formations of Valley of the Whales.\\n\\nWhatever you choose to do, the Auberge is the ideal base which also provides you with luxuriously furnished and tastefully furnished rooms. Relax in the tranquil and peaceful atmosphere of your room and quietly admire the stunning view of the landscape. This is truly an oasis and your perfect place to rest.\nWhatever you choose to do, the Auberge is the ideal base which also provides you with luxuriously furnished and tastefully furnished rooms. Relax in the tranquil and peaceful atmosphere of your room and quietly admire the stunning view of the landscape. This is truly an oasis and your perfect place to rest.",
        "email": "auberge.fayoum@helnan.com",
        "id": 24,
        "name": "HELNANA UBERGE HOTEL",
        "originalImage": "image/100532211.jpg",
        "user_id": 5,
        "villa": 0,
        "web": "www.facebook.com/helnanaubergehotel"
    },
    {
        "City": "fayoum",
        "Double": 10,
        "Phone": "(+20)100-624-7051",
        "Single": 0,
        "Sweet": 0,
        "TotalBeds": 0,
        "Triple": 0,
        "address": "Tunis village",
        "chalet": 4,
        "coordinatesX": 29.399535508014626,
        "coordinatesY": 30.490833420044055,
        "description": "Palm shadow resort in Tunis features a terrace and barbecue facilities. Offering a restaurant, the property also has a garden, as well as an indoor pool. The property has a 24-hour front desk, airport transportation, a kids' club and free WiFi.\\nSome rooms have a kitchen with a fridge and a microwave.\\nAn à la carte breakfast is available each morning at the hotel.\\nThe area is popular for cycling, and car rental is available at palm shadow resort.Spread over the fabulous coasts of Lake Karoun, the former hunting lodge of King Farouk offers an elegant atmosphere and a number of activities. Enjoy the unspoiled countryside and take a stroll along the golden sandy beach. Go fishing, boat sailing or windsurfing. Take a short excursion to visit the famous Seven Waterwheels or explore the unique rock formations of Valley of the Whales.\n\nWhatever you choose to do, the Auberge is the ideal base which also provides you with luxuriously furnished and tastefully furnished rooms. Relax in the tranquil and peaceful atmosphere of your room and quietly admire the stunning view of the landscape. This is truly an oasis and your perfect place to rest.",
        "email": "magdisidhom@hotmail.com",
        "id": 27,
        "name": "Palm Shadows",
        "originalImage": "image/palm.jpg",
        "user_id": 5,
        "villa": 1,
        "web": "www.fayoum-palmshadow"
    }
]