# Generated by Django 4.2 on 2023-05-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0003_auto_20230324_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplaces',
            name='originalImage',
            field=models.ImageField(upload_to='image/%y/%m/%d'),
        ),
    ]
