# Generated by Django 4.2 on 2023-05-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0007_alter_postimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
