# Generated by Django 4.2 on 2023-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0008_remove_postimage_post_delete_post_delete_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
