# Generated by Django 4.2 on 2023-05-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0022_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
