# Generated by Django 4.2 on 2023-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0027_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='touristplaces',
            name='favourite',
            field=models.ManyToManyField(default='', to='FayTourApp.favourite'),
        ),
    ]
