# Generated by Django 4.2 on 2023-05-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0029_favoritetouristplace_remove_touristplaces_favourite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteTouristPlace',
            new_name='Favorite',
        ),
    ]
