# Generated by Django 4.2 on 2023-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0030_rename_favoritetouristplace_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
