# Generated by Django 4.2 on 2023-05-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0032_rename_placeid_favorite_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
