# Generated by Django 4.2 on 2023-05-31 03:48

import FayTourApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0035_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(blank=True, default='', unique=True, upload_to=FayTourApp.models.get_unique_filename),
        ),
    ]
