# Generated by Django 3.2.10 on 2023-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0041_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='hotel',
        ),
        migrations.AddField(
            model_name='favorite',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.hotel'),
        ),
    ]
