# Generated by Django 3.2.10 on 2023-06-22 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FayTourApp', '0043_favorite_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='fav',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
