# Generated by Django 3.2 on 2023-07-07 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FayTourApp', '0045_auto_20230622_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplaces',
            name='originalImage',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritehotel',
            unique_together={('user', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritetouristplaces',
            unique_together={('user', 'touristPlaces')},
        ),
        migrations.AlterIndexTogether(
            name='favoritehotel',
            index_together={('user', 'hotel')},
        ),
        migrations.AlterIndexTogether(
            name='favoritetouristplaces',
            index_together={('user', 'touristPlaces')},
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('adulls', models.PositiveSmallIntegerField()),
                ('kids', models.PositiveSmallIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FayTourApp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
                'index_together': {('user', 'post')},
            },
        ),
    ]
